# Generated by Django 2.2 on 2020-02-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200103_0613'),
        ('profiles', '0003_auto_20200102_1042'),
    ]

    operations = [
    ]
