# Generated by Django 2.2.6 on 2019-11-28 12:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_teacherprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentProfile',
            new_name='Profile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
