# Generated by Django 2.2.10 on 2020-02-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mandatory',
        ),
    ]
