# Generated by Django 2.2 on 2020-02-13 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200213_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credits',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
